nameOverride: "adservice"

replicaCount: 1

image:
  repository: adservice
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9555
  targetPort: 9555
  portName: grpc

  # HTTP probe değil, gRPC probe kullanılacak
  livenessProbe:
    enabled: false   # http'yi kapatıyoruz

  readinessProbe:
    enabled: false

  # gRPC probelar
  grpcProbe:
    enabled: true
    port: 9555
    initialDelaySeconds: 20
    periodSeconds: 15

  startupProbeGrpc:
    enabled: false  # istersen açarsın

env:
  - name: PORT
    value: "9555"

serviceAccount:
  create: true
  name: "adservice"

resources:
  requests:
    cpu: "200m"
    memory: "180Mi"
  limits:
    cpu: "300m"
    memory: "300Mi"

securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
