replicaCount: 1

image:
  repository: my-nexus-repository-manager.nexus.svc.cluster.local:8082/repository/nexusimagerepository/hepsheetapi
  tag: managed-by-jenkins
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-regcred

nameOverride: "hepsheetapi"
fullnameOverride: "hepsheetapi"

serviceAccount:
  create: true
  annotations: {}
  name: "hepsheetapi"

podSecurityContext: 
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  privileged: false
  capabilities:
    drop:
      - ALL


service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  livenessProbe:
    enabled: false
    path: "/"
    port: http
  readinessProbe:
    enabled: false
    path: "/"
    port: http




ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  pathType: Prefix
  activeService: true
  hosts:
    - host: hepsheetapi.hepapi.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hepsheetapi-hepapi-tls
      hosts:
        - hepsheetapi.hepapi.com

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


tolerations: []
affinity: {}

externalSecret:
  name: hepsheetapi-external-secret
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: hepsheetapi-external-secret
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: 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
        property: GOOGLE_CLIENT_SECRET
    - secretKey: DB_HOST
      remoteRef:
        key: ulaq-test-db.cluster-cuxejpmehjle.eu-west-1.rds.amazonaws.com
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: 5432
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: hepsheet
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: hepsheet2024!
        property: DB_PASSWORD
    - secretKey: DB_NAME
      remoteRef:
        key: hepsheet
        property: DB_NAME
    - secretKey: DB_SCHEMA
      remoteRef:
        key: public
        property: DB_SCHEMA
    - secretKey: ADMIN_NAME
      remoteRef:
        key: Ümit Özdemir
        property: ADMIN_NAME
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: umit@hepapi.com
        property: ADMIN_EMAIL
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: adminpassword
        property: ADMIN_PASSWORD
    - secretKey: ADMIN_TITLE
      remoteRef:
        key: Administrator
        property: ADMIN_TITLE
    - secretKey: DEFAULT_PASSWORD
      remoteRef:
        key: hepapi1234
        property: DEFAULT_PASSWORD

extraConfigMap:
  name: hepsheet-extra-cm
  data:
    GOOGLE_CLIENT_ID: 1035129365942-p7o81tm5fb8q9j6493jceabddf848uje.apps.googleusercontent.com
    GOOGLE_REDIRECT_URI: https://hepsheet.hepapi.com/api/auth/callback/google
    PRETTY: 1
    LOG_LEVEL: debug
    DAILY_WORK_HOURS: 8

