replicaCount: 1

image:
  repository: managed-by-jenkins
  tag: managed-by-jenkins
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-regcred

nameOverride: "identity-api"
fullnameOverride: "identity-api"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  instrumentation.opentelemetry.io/inject-dotnet: monitoring/dotnet-instrumentation-100

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  livenessProbe:
    enabled: false
    path: "/health"
    port: http
  readinessProbe:
    enabled: false
    path: "/health"
    port: http

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
  className: "nginx"
  pathType: Prefix
  activeService: true
  hosts:
    - host: identity.hepapi.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: identity-hepapi-tls
      hosts:
        - identity.hepapi.com

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}

extraConfigMap: null

env:
  - name: ASPNETCORE_URLS
    value: "http://+:8080"
  - name: IdentityServer__IssuerUri
    value: "https://identity.hepapi.com"
  - name: ConnectionStrings__identitydb
    value: "Host=postgres.database;Database=identitydb;Username=postgres;Password=postgres"
  - name: WebAppClient
    value: "https://eshop.hepapi.com"
  - name: WebhooksWebClient
    value: "https://webhooksclient.hepapi.com"
  - name: WebhooksApiClient
    value: "http://webhooks-api"
  - name: BasketApiClient
    value: "http://basket-api"
  - name: OrderingApiClient
    value: "http://ordering-api"
  - name: MauiCallback
    value: "https://maui.hepapi.com"
