replicaCount: 1

image:
  repository: managed-by-jenkins
  tag: managed-by-jenkins
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-regcred

nameOverride: "webapp"
fullnameOverride: "webapp"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1654
securityContext:
  runAsUser: 1654
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  livenessProbe:
    enabled: false
    path: "/health"
    port: http
  readinessProbe:
    enabled: false
    path: "/health"
    port: http

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  className: "nginx"
  pathType: Prefix
  activeService: true
  hosts:
    - host: eshop.hepapi.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: eshop-hepapi-tls
      hosts:
        - eshop.hepapi.com

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations: []
affinity: {}

initContainers:
  - name: fix-permissions
    image: busybox:latest
    command: ["sh", "-c", "chown -R 1654:1654 /app/keys && chmod -R 755 /app/keys"]
    volumeMounts:
      - name: webapp-volume
        mountPath: /app/keys
    securityContext:
      runAsUser: 0

extraConfigMap: null

# PVC i√ßin
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /app/keys
  annotations:
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/sync-options": Prune=false

env:
  - name: ASPNETCORE_URLS
    value: "http://+:8080"
  - name: ASPNETCORE_ENVIRONMENT
    value: "Development"
  - name: ASPNETCORE_DATA_PROTECTION__KEYS_DIRECTORY
    value: "/app/keys"
  - name: DataProtection__ApplicationDiscriminator
    value: "eShop.WebApp"
  - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
    value: "true"
  - name: ASPNETCORE_HTTPS_PORT
    value: "443"
  - name: ConnectionStrings__EventBus
    value: "amqp://eventbus"
  - name: IdentityUrl
    value: "https://identity.hepapi.com"
  - name: IdentityUrlExternal
    value: "https://identity.hepapi.com"
  - name: CallBackUrl
    value: "https://eshop.hepapi.com"
  - name: PushedAuthorizationBehavior
    value: "Disable"
  - name: RequireHttpsMetadata
    value: "false"
